site_name: Obsidian
site_description: 'Obsidian.md Notes via Mkdocs.'
site_author: 'relgisri'
docs_dir: './test'
repo_url: https://github.com/relgisri/obsidian-vault
dev_addr: '127.0.0.1:8000'

# Fail to build if we have broken links
strict: false

# Copyright
copyright: 'Copyright &copy; 2021 relgisri'

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

theme:
  name: material  
  language: en
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  feature:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  font:
    text: 'Roboto'
    code: 'Cascadia Code PL'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/relgisri
    - type: fontawesome/brands/twitter
      link: https://twitter.com/0xE02B7
